# Generated by Django 4.2.4 on 2023-08-07 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='devices/')),
                ('key_features', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_storage', models.CharField(max_length=50)),
                ('expandable_storage', models.CharField(blank=True, max_length=50, null=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='phones.device')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=10)),
                ('where_to_buy', models.TextField()),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='phones.device')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(max_length=200)),
                ('ram', models.CharField(max_length=50)),
                ('speed', models.CharField(max_length=200)),
                ('multitasking', models.CharField(max_length=200)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='phones.device')),
            ],
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_size', models.CharField(max_length=50)),
                ('screen_resolution', models.CharField(max_length=50)),
                ('screen_quality', models.CharField(max_length=200)),
                ('colors', models.CharField(max_length=200)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='phones.device')),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_camera', models.CharField(max_length=100)),
                ('secondary_camera', models.CharField(max_length=100)),
                ('photo_quality', models.CharField(max_length=200)),
                ('video_quality', models.CharField(max_length=200)),
                ('special_features', models.TextField()),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='phones.device')),
            ],
        ),
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.CharField(max_length=50)),
                ('charging_speed', models.CharField(max_length=200)),
                ('wireless_charging', models.BooleanField()),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='phones.device')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_resistance', models.BooleanField()),
                ('operating_system', models.CharField(max_length=200)),
                ('security_features', models.TextField()),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='phones.device')),
            ],
        ),
    ]
