# Generated by Django 4.2.4 on 2023-09-08 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=210, unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='brands.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headphones', models.CharField(max_length=500)),
                ('speakers', models.CharField(max_length=500)),
                ('screen_mirroring', models.CharField(max_length=500)),
                ('additional_microphones', models.CharField(max_length=500)),
                ('phone', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multimedia', to='phones.phone')),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_chip', models.CharField(max_length=500)),
                ('processor', models.CharField(max_length=500)),
                ('gpu', models.CharField(max_length=500)),
                ('ram', models.CharField(max_length=500)),
                ('internal_storage', models.CharField(max_length=500)),
                ('storage_expansion', models.CharField(max_length=500)),
                ('device_type', models.CharField(max_length=500)),
                ('os', models.CharField(max_length=500)),
                ('phone', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hardware', to='phones.phone')),
            ],
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=500)),
                ('resolution', models.CharField(max_length=500)),
                ('technology', models.CharField(max_length=500)),
                ('refresh_rate', models.CharField(max_length=500)),
                ('screen_to_body_ratio', models.CharField(max_length=500)),
                ('features', models.TextField()),
                ('phone', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='display', to='phones.phone')),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensions', models.CharField(max_length=500)),
                ('weight', models.CharField(max_length=500)),
                ('materials', models.CharField(max_length=500)),
                ('resistance', models.CharField(max_length=500)),
                ('biometrics', models.CharField(max_length=500)),
                ('keys', models.CharField(max_length=500)),
                ('colors', models.TextField()),
                ('phone', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='design', to='phones.phone')),
            ],
        ),
        migrations.CreateModel(
            name='ConnectivityAndFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bluetooth', models.CharField(max_length=500)),
                ('wifi', models.CharField(max_length=500)),
                ('usb', models.CharField(max_length=500)),
                ('features', models.TextField()),
                ('location', models.CharField(max_length=500)),
                ('sensors', models.CharField(max_length=500)),
                ('other', models.TextField()),
                ('phone', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connectivity_and_features', to='phones.phone')),
            ],
        ),
        migrations.CreateModel(
            name='Cellular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('five_g', models.CharField(max_length=500)),
                ('four_g_fdd', models.CharField(max_length=500)),
                ('four_g_tdd', models.CharField(max_length=500)),
                ('three_g', models.CharField(max_length=500)),
                ('data_speed', models.CharField(max_length=500)),
                ('dual_sim', models.CharField(max_length=500, null=True)),
                ('sim_type', models.CharField(max_length=500)),
                ('phone', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cellular', to='phones.phone')),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rear', models.CharField(max_length=500)),
                ('main_camera', models.CharField(max_length=500)),
                ('specifications', models.CharField(max_length=500)),
                ('second_camera', models.CharField(max_length=500)),
                ('third_camera', models.CharField(max_length=500)),
                ('video_recording', models.CharField(max_length=500)),
                ('front', models.CharField(max_length=500)),
                ('phone', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camera', to='phones.phone')),
            ],
        ),
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.CharField(max_length=500)),
                ('charging', models.CharField(max_length=500)),
                ('max_charge_speed', models.CharField(max_length=500)),
                ('phone', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battery', to='phones.phone')),
            ],
        ),
    ]
