# Generated by Django 4.2.4 on 2023-08-08 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='phones/images/')),
                ('key_features', models.TextField()),
                ('price', models.FloatField()),
                ('currency', models.CharField(max_length=10)),
                ('where_to_buy', models.TextField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.brand')),
            ],
        ),
        migrations.RemoveField(
            model_name='price',
            name='device',
        ),
        migrations.RemoveField(
            model_name='additionalfeatures',
            name='device',
        ),
        migrations.RemoveField(
            model_name='battery',
            name='device',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='device',
        ),
        migrations.RemoveField(
            model_name='display',
            name='device',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='device',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='device',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.AddField(
            model_name='additionalfeatures',
            name='phone',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='phones.phone'),
        ),
        migrations.AddField(
            model_name='battery',
            name='phone',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='phones.phone'),
        ),
        migrations.AddField(
            model_name='camera',
            name='phone',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='phones.phone'),
        ),
        migrations.AddField(
            model_name='display',
            name='phone',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='phones.phone'),
        ),
        migrations.AddField(
            model_name='performance',
            name='phone',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='phones.phone'),
        ),
        migrations.AddField(
            model_name='storage',
            name='phone',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='phones.phone'),
        ),
    ]
