# Generated by Django 4.2.4 on 2023-08-09 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_phone_remove_price_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalfeatures',
            name='phone',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_features', to='phones.phone'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='phone',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battery', to='phones.phone'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='phone',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camera', to='phones.phone'),
        ),
        migrations.AlterField(
            model_name='display',
            name='phone',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='display', to='phones.phone'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='phone',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='phones.phone'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='phone',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='phones.phone'),
        ),
    ]
