# Generated by Django 4.2.4 on 2023-08-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0006_phone_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalfeatures',
            name='operating_system',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='battery',
            name='capacity',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='battery',
            name='charging_speed',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='camera',
            name='photo_quality',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='camera',
            name='primary_camera',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='camera',
            name='secondary_camera',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='camera',
            name='video_quality',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='display',
            name='colors',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='display',
            name='screen_quality',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='display',
            name='screen_resolution',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='display',
            name='screen_size',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='performance',
            name='cpu',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='performance',
            name='multitasking',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='performance',
            name='ram',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='performance',
            name='speed',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='storage',
            name='expandable_storage',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='internal_storage',
            field=models.CharField(max_length=500),
        ),
    ]
