# Generated by Django 4.2.4 on 2023-08-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0007_alter_additionalfeatures_operating_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='release_date',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
